### ISSUE TITLE
Feature Request: Link out to descriptions/recommendation on test failures 

### ISSUE THREAD

**Issue by jedsalazar** [edera-dev/am-i-isolated#20]
docs.edera.dev should have an Am I Isolated section that gives a documented breakdown on each of the failing tests and why they're important.

**Comment by denhamparry** [comment]
We should use the format `AII****` to track test failures:

* `AII` - Am I Isolated
* `2200`
  * First two numbers start at `20` for search filter
  * Try to group by the first two numbers into a group of tests
  * Second two numbers reference specific test

e.g.
```txt
AII2200
AII2201
AII2202
AII2300
AII2301
```
