### ISSUE TITLE
Feature request: Detect host resources

### ISSUE THREAD

**Issue by jedsalazar** [edera-dev/am-i-isolated#6]
Detect dangerous host resources available to a container as specified in the `securityContext` of a podspec. These include

```
hostNetwork
hostPID
hostIPC
hostPath
hostPort
```

**Comment by kaniini** [comment]
Cannot find an observable indicator that `hostPath` or `hostPort` are in use from inside the workload.  The rest can be detected based on namespace ID less than `0xf0000002`.
